id: 32a2f6e2b5a8417ea56696b8db6aa2b1
title: Toh_182-The_Perfection_of_Generosity-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-002
  eft-text-version: 1.18 2019
